services:
  go-article:
    container_name: go-article
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - database
    restart: unless-stopped
    command: ["./go-article"]
    
  database:
    image: postgres:latest
    container_name: go-article-db
    environment:
      POSTGRES_DB: article_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


networks:
  app-net:

volumes:
  postgres-data:
    name: go-article-postgres-data
